spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SecureApiDB
    username: postsecure
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      dialect: org.hibernate.dialect.PostgreSQLDialect
